objects/Credit_Card_Type_Number_Validation__mdt.object
<CustomObject>
    <fields>
        <fullName>Maximum_Charecter__c</fullName>
        <label>Maximum Charecter</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Charecter__c</fullName>
        <label>Minimum Charecter</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Starts_With__c</fullName>
        <label>Starts With</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Credit Card Type Number Validation</label>
    <pluralLabel>Credit Card Type Number Validation</pluralLabel>
</CustomObject>

objects/IDEXX_Domain_Values__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Cost_Center_For_Rep__c</fullName>
        <label>Default Cost Center For Rep</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>IDEXX Domain Values</label>
    <nameField>
        <label>Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IDEXX Domain Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OrderCreationUtil.cls
/****************************************************************************
* Apex Class Name    : OrderCreationUtil
* Description        : Utility Class for the Order Create Wizard
                       
* Modification Log   : 
* ---------------------------------------------------------------------------
* Developer                   Date                   Description
* ---------------------------------------------------------------------------
* Raushan Anand             Feb 19 2016                 Created    
                                                   
****************************************************************************/
public with sharing class OrderCreationUtil {
    //Properties for Idexx Domain Value
    public static List<IDEXX_Domain_Values__c> domValList {
          get {
               if (domValList == null) {
                    domValList = [SELECT Name,Code__c,Description__c,Default_Cost_Center_For_Rep__c FROM IDEXX_Domain_Values__c WHERE Name!=:null and Active__c=:true ORDER BY Description__c ASC];
               }

               return domValList;
          }
          set;
     }
    //Properties for Credit Card Validation
    public static List<Credit_Card_Type_Number_Validation__mdt> ccValidationList {
          get {
               if (ccValidationList == null) {
                    ccValidationList = [SELECT Label, Minimum_Charecter__c,Maximum_Charecter__c,Starts_With__c FROM Credit_Card_Type_Number_Validation__mdt LIMIT 10];
               }
               return ccValidationList;
          }
          set;
     }
}